### PR TITLE
fixed README's code blocks

### PR DESCRIPTION
**Pull request by lihuanshuai**
these code blocks in README did not work the right way, I just fixed them

### CODE REVIEW

**Comment by ijc25** [comment]
Thanks. I wonder why the three code blocks further up the file which look to be identically indented to this one render fine in https://github.com/docker/hyperkit/blob/master/README.md.

In any case perhaps we should markup all of the code blocks using the "```sh" syntax?

**Comment by rneugeba** [comment]
Thanks for the fix.

**Comment by ijc25** [comment]
BTW, the reason for the difference is that it immediately follows a bulleted list. Seems like it could also have been fixed by indenting by 8 spaces instead of 4 (4 for the bullet list and another 4 for the fixed formatting).

**Comment by lihuanshuai** [comment]
@ijc25 you are right. in fact, 6 spaces is enough for  this case, but an indention with more 4 space is not a good choice in markdown.

**Comment by rneugeba** [comment]
apologies, was a bit to trigger happy merging this. The resulting README.md looked fine, but it would be good to fix this properly

**Pull request merged**
