### PR TITLE
Rename com.docker.hyperkit to hyperkit

### PR DESCRIPTION
**Pull request by djs55**
The name `hyperkit`

- is a more conventional format name
- matches the name of the github repo
- is shorter and easier to type
- is consistent with vpnkit (repo = vpnkit; binary = vpnkit)

Signed-off-by: David Scott <dave.scott@docker.com>

### CODE REVIEW

**Comment by ijc25** [comment]
CI failure is 
```
opam remote add mirageos-3-beta git://github.com/mirage/mirageos-3-beta

[ERROR] Could not fetch repo

opam remote add mirageos-3-beta git://github.com/mirage/mirageos-3-beta returned exit code 66
```

Not related to this PR but could you sort that out and then rebase?

**Comment by samoht** [comment]
No need for that remote anymore as Mirage3 has been released to the mainstream repo last week.

**Comment by djs55** [comment]
Will do!

**Comment by djs55** [comment]
Rebase is done and CI is green. WDYT?

**Comment by avsm** [comment]
LGTM

**Comment by ijc25** [comment]
Seems like a bit of a bikeshed issue, but your given reasons seem sound enough lets go with it.

**Pull request merged**
