### PR TITLE
ocaml: if a Mirage thread fails, ensure we fail the request

### PR DESCRIPTION
**Pull request by djs55**
The Mirage I/O operations are supposed to return a result type as follows:

    [ `Ok of result | `Error of error description ]

If the implementation actually fails i.e. by raising an exception, this would
propagate and prevent the client request ever returning. This patch catches
stray exceptions, logs something about them, and returns an error to the
caller.

Signed-off-by: David Scott <dave.scott@docker.com>

### CODE REVIEW

**Comment by ijc25** [comment]
```
$ git fetch origin pull/91/head
From github.com:docker/hyperkit
 * branch            refs/pull/91/head -> FETCH_HEAD
$ git diff -b origin/master FETCH_HEAD -- src/lib/mirage_block_ocaml.ml 
diff --git a/src/lib/mirage_block_ocaml.ml b/src/lib/mirage_block_ocaml.ml
index f9554eb..49b43a0 100644
--- a/src/lib/mirage_block_ocaml.ml
+++ b/src/lib/mirage_block_ocaml.ml
@@ -283,7 +283,10 @@ let process_one t =
   let open Protocol in
   let open Mirage_block.Error.Monad in
   let open Mirage_block.Error.Monad.Infix in
-  let result_t = match t.request with
+  let result_t =
+    Lwt.catch
+      (fun () ->
+        match t.request with
           | Request.Connect (block_config, qcow_config) ->
             Block.of_config block_config
             >>= fun base ->
@@ -350,12 +353,20 @@ let process_one t =
             let n = Int64.div len sector_size in
             Qcow.discard t.Handle.block ~sector ~n ()
             >>= fun () ->
-      return (Response.Delete)
+            return Response.Delete
           | Request.Flush h ->
             let t = Handle.find_or_quit h in
             Block.flush t.Handle.base
             >>= fun () ->
-      return Response.Flush in
+            return Response.Flush
+      )
+      (fun e ->
+        (* If the thread fails unexpectedly then convert this into an Error return
+           to guarantee we return an error code to the block interface instead of
+           dropping the request on the floor. *)
+        Log.err (fun f -> f "Mirage block device raised exception: %s" (Printexc.to_string e));
+        Lwt.return (`Error (`Unknown (Printexc.to_string e)))
+      ) in
   let open Lwt in
   result_t >>= fun result ->
   Ivar.fill t.ivar result;
```

LGTM, I also had a quick look through the resulting code which looks fine also.

**Comment by djs55** [comment]
Thanks! I just realised this branch doesn't contain the new CI tests. I'll rebase onto latest master just in case.

**Comment by ijc25** [comment]
Good idea.

**Comment by djs55** [comment]
OK, CI with the new tests is happy.

**Pull request merged**
