### PR TITLE
Introduce support for Dtrace static trace points

### PR DESCRIPTION
**Pull request by pborzenkov**
This pull request adds all the build system bits needed to support static DTrace trace points and defines one sample trace point as an example.

DTrace provides a great ability to dig inside a running system with little to none overhead and will be of great help during performance investigations.

Example usage is shown in the second commit message.

### CODE REVIEW

**Comment by avsm** [comment]
Awesome!  Any chance of a README describing a simple usage from the CLI?  Also, have you managed to trace into the Hypervisor framework in the kernel?

**Comment by pborzenkov** [comment]
Sure, will add a snippet to README.

I haven't yet tried to trace Hypervisor.kext, but I believe it should be possible with 'fbt' (Function Boundary Tracing) provider.
But I failed to do this on the first try. Looks like Apple have changed something in Yosemite and either they do not support fbt provider anymore, or they've disabled it by default (probably, due to security reasons). I'll dig into this later.

**Comment by rneugeba** [comment]
@pborzenkov Thanks for the patches. They LGTM. @ijc25 do you want to take a look too?

**Comment by pnasrat** [comment]
I am not a maintainer but awesome just tested this locally I had looked at starting something similar but hadn't got as far - note I'm running with [SIP](https://derflounder.wordpress.com/2015/10/01/system-integrity-protection-adding-another-layer-to-apples-security-model/) disabled for dtrace:
```
$ csrutil status | grep DTrace
	DTrace Restrictions: disabled
```
```
sudo dtrace -l -m com.docker.hyperkit
   ID   PROVIDER            MODULE                          FUNCTION NAME
 8319 hyperkit15739 com.docker.hyperkit                      block_preadv block-preadv
 8320 hyperkit15739 com.docker.hyperkit                      block_preadv block-preadv-done
 8321 hyperkit15739 com.docker.hyperkit                     block_pwritev block-pwritev
 8322 hyperkit15739 com.docker.hyperkit                     block_pwritev block-pwritev-done
 8323 hyperkit15739 com.docker.hyperkit                           vmx_run vmx-ept-fault
 8324 hyperkit15739 com.docker.hyperkit                           vmx_run vmx-exit
 8325 hyperkit15739 com.docker.hyperkit                           vmx_run vmx-inject-virq
 8326 hyperkit15739 com.docker.hyperkit                           vmx_run vmx-read-msr
 8327 hyperkit15739 com.docker.hyperkit                           vmx_run vmx-write-msr
```

It'd be nice if the `README` or a seperate `DEBUGGING.md` section had an example of using dtrace more than just the query. This could easily be a follow up and no need to block on this. I'm just re-learning dtrace but you could probably do something more interesting than this:

```
sudo dtrace -n 'hyperkit15739:::vmx-exit { @num["exit"] = count();  }'
dtrace: description 'hyperkit15739:::vmx-exit ' matched 1 probe
^C

  exit                                                           2655
```

For comparison the postgresql docs on dynamic tracing. https://www.postgresql.org/docs/9.4/static/dynamic-trace.html

**Comment by pnasrat** [comment]
@pborzenkov  Note that following the steps to disable SIP as linked above seems to enable fbt provider for me not tested out. May be useful to note steps for hyperkit contributors or kernel developers

* Boot into recovery using Cmd-R
* `csrutil enable --without dtrace`
* Reboot
* `csrutil status`

I haven't looked at xnu in depth but eg:

```
 sudo dtrace -lP fbt | grep hv_ | tail
267144        fbt       mach_kernel                      hv_set_traps return
267145        fbt       mach_kernel                  hv_release_traps entry
267146        fbt       mach_kernel                  hv_release_traps return
267147        fbt       mach_kernel                  hv_set_callbacks entry
267148        fbt       mach_kernel                  hv_set_callbacks return
267149        fbt       mach_kernel              hv_release_callbacks entry
267150        fbt       mach_kernel              hv_release_callbacks return
267151        fbt       mach_kernel                        hv_suspend entry
267152        fbt       mach_kernel                      hv_task_trap entry
267153        fbt       mach_kernel                    hv_thread_trap entry
```

Also can see `com.apple.driver.AppleHV` module full provider list https://gist.github.com/pnasrat/150740803fc00a86c60ee70b5892485d

**Comment by pborzenkov** [comment]
@pnasrat Thanks!

**Comment by ijc25** [comment]
LGTM, thanks @pborzenkov and everyone who commented.

**Pull request merged**
